---
title: "Module 4 Pair Quiz"
author: "KoiBaplog"
date: "7/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# {.tabset} 

## Question 1 

### An article in the Journal of Sound and Vibration ["Measurement of Noise-Evoked Blood Pressure by Means of Averaging Method: Relation between Blood Pressure Rise and PSL" (1991, Vol. 151(3), pp. 383-394)] described a study investigating the relationship between noise exposure and hypertension. The following data are representative of those reported in the article.

### <span style="color:red">A. Draw a scatter diagram of $y$ (blood pressure rise in millimeters of mercury) versus $x$ (sound pressure level in decibels). Does a simple linear regression model seem reasonable in this situation? </span>

``` {R}
y <- c(1,	0,	1,	2,	5,	1,	4,	6,	2,	3,	5,	4,	6,	8,	4,	5,	7,	9,	7,	6)
 
x <- c(60,	63,	65,	70,	70,	70,	80,	90,	80,	80,	85,	89,	90,	90,	90,	90,	94,	100,	100,	100)

plot(x, y, pch = 16, cex = 1, col = "red", main = "Scatter Plot of Blood Pressure Rise and Sound Pressure Level", xlab = "Sound Pressure Level (db)", ylab = "Blood Pressure Rise (mm)")

```

After observing the scatter plot above, it seems likely that there is a linear relationship between the two variables.

### <span style="color:red">B. Fit the simple linear regression model using least squares. Find an estimate of $\sigma^2$</span>

``` {R}
plot(x, y, pch = 16, cex = 1, col = "red", main = "Scatter Plot of Blood Pressure Rise and Sound Pressure Level", xlab = "Sound Pressure Level (db)", ylab = "Blood Pressure Rise (mm)")

model <- lm(y ~ x)

model

abline(model)
```

The plot shows the same scatter plot but with a linear regression model fitted on it. The <code> lm() </code> function provides a linear regression model using least squares. The resulting linear regression model is given by the equation:

\begin{aligned}

\hat{y} = -10.1315 + 0.1743x

\end{aligned}

The formula for an estimate of $\sigma^2$ is given by the formula:

\begin{aligned}

\sigma^2 = \frac{SS_E}{n - 2}

\end{aligned}

where $SS_E$ is the **error sum of squares** and $n = 20$ is the number of samples.

The function <code> deviance() </code> gives the $SS_E$ of the linear regression model of the dataset.

```{R}

deviance(model)

```

\begin{aligned}

\sigma^2 = \frac{31.26647}{20 - 2}

\\

\sigma^2 = 1.737026

\end{aligned}

### <span style="color:red">C. Find the predicted mean rise in blood pressure level associated with a sound pressure level of $85$ decibels.</span>

This is obtained simply by substituting $x = 85$ in the linear regression model.

\begin{aligned}

\hat{y} = -10.1315 + 0.1743 * 85 = 4.684

\end{aligned}

With a sound pressure level of $85$, the predicted mean rise in blood pressure level is $4.684$.
